component_depth: 1
languages:
- name: typescript
  production:
    exclude:
      - /benchmarks/.*
      - /integration/.*
      - /sample/.*
      - /tools/.*
      - .*spec.ts
  test:
    include:
      - .*spec.ts
